port: 8080
address: 127.0.0.1

baseURL: http://localhost:8080

title: Epigram Demo
description: A place to record quotes.

repo: inmemory

trustProxy: false

OIDCProvider:
  name: google
  issuerURL: "https://accounts.google.com"
  clientId: "1234567890.apps.googleusercontent.com"
  clientSecret: "your-client-secret"

entryQuestions:
  - question: What is the best color?
    answer: purple
  - question: What is the best animal?
    answer: dog
