package service

import (
	"strconv"
	"strings"
)

// ServiceError is used to represeent errors generated by services, which may contian
// more than one issue in order to provide the best feedback to the user.
type ServiceError struct {
	// StatusCode is a numeric code which identifies the category of this error using
	// the HTTP status code standard (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status).
	StatusCode int
	// Issues is an array of strings which represents the descriptive, human readable
	// errors that should be presented to the user.
	Issues []string
}

// Error returns the status code followed by a concatenation of all the issues in this
// ServiceError.
func (e ServiceError) Error() string {
	return strconv.Itoa(e.StatusCode) + ": " + strings.Join(e.Issues, " ")
}

// HasIssues returns true if there is more than one issue in this ServiceError. If
// false, no issues were added, and this ServiceError should not be treated as an error.
func (e ServiceError) HasIssues() bool {
	return len(e.Issues) > 0
}

// addIssue adds an issue to this ServiceError
func (e *ServiceError) addIssue(iss string) {
	e.Issues = append(e.Issues, iss)
}
